### ISSUE TITLE
js error in results.js

### ISSUE THREAD

**Issue by nczirjak-acdh** [acdh-oeaw/repo-theme#15]
https://fedora.hephaistos.arz.oeaw.ac.at/browser/oeaw_detail/aHR0cHM6Ly9mZWRvcmEuaGVwaGFpc3Rvcy5hcnoub2Vhdy5hYy5hdC9yZXN0L2NiLzk5L2E2L2ZlL2NiOTlhNmZlLTM4YzktNDJjZi05ZjIzLWExMDQ0MDY1NDBjNw==

Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at HTMLDocument.<anonymous> (results.js?oxcwkk:287)
    at j (jquery.min.js?v=3.2.1:2)
    at k (jquery.min.js?v=3.2.1:2)

**Comment by asilcetin** [comment]
good catch, should be fixed now.
